# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcrOE6HXcN7-IHcoi-BMBZQI36Zd5FAs
"""

# Commented out IPython magic to ensure Python compatibility.
import streamlit as st
import pandas as pd
import plotly.express as px
# 
st.title("📊 AI Financial Market Dashboard")
# 
# # LOAD DATA (from Colab uploaded file)
 df = pd.read_csv("financial_data.csv", encoding='latin1')
# 
df.columns = df.columns.str.strip()
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna()
# 
# # SIDEBAR FILTERS
st.sidebar.header("Filters")
# 
company = st.sidebar.selectbox("Select Company", df["Company"].unique())
# 
 date_range = st.sidebar.date_input(
     "Select Date Range",
     [df["Date"].min(), df["Date"].max()]
 )
# 
 filtered = df[
    (df["Company"] == company) &
    (df["Date"] >= pd.to_datetime(date_range[0])) &
    (df["Date"] <= pd.to_datetime(date_range[1]))
]
# 
# # TABLE
st.subheader("Filtered Data")
 st.dataframe(filtered)
# 
# # CHARTS
 st.subheader("Revenue Over Time")
 fig1 = px.line(filtered, x="Date", y="AI_Revenue_USD_Mn")
 st.plotly_chart(fig1)
# 
 st.subheader("R&D Spending")
 fig2 = px.bar(filtered, x="Date", y="R&D_Spending_USD_Mn")
 st.plotly_chart(fig2)
# 
 st.subheader("Growth vs Stock Impact")
 fig3 = px.scatter(filtered,
                   x="AI_Revenue_Growth_%",                   y="Stock_Impact_%",
                   color="Event")
 st.plotly_chart(fig3)
# 
# # KPIs
 st.subheader("Average Metrics")
 col1, col2, col3 = st.columns(3)
# 
 col1.metric("Avg Revenue", round(filtered["AI_Revenue_USD_Mn"].mean(), 2))
 col2.metric("Avg Growth %", round(filtered["AI_Revenue_Growth_%"].mean(), 2))
 col3.metric("Avg Stock Impact %", round(filtered["Stock_Impact_%"].mean(), 2))
# 
# # TOP RECORDS
 st.subheader("Top 5 Highest Revenue")
 st.dataframe(filtered.sort_values(by="AI_Revenue_USD_Mn", ascending=False).head(5))
 
 st.subheader("Top 5 Lowest Revenue")
 st.dataframe(filtered.sort_values(by="AI_Revenue_USD_Mn", ascending=True).head(5))